AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for Mini Sentra Exercise"

Resources:
  # S3 Bucket for Results
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sentra-results-bucket
    DeletionPolicy: Retain

  # SNS Topic
  ResultsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sentra-results-topic
    DeletionPolicy: Retain

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SentraLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SentraS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject  
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"
    DeletionPolicy: Retain

  # Lambda Function
  SentraScannerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SentraScanner
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: sentra-prototype-source-code
        S3Key: lambda_mail_scanner.zip
      Handler: lambda_mail_scanner.lambda_handler
      
      Environment:
        Variables:
          RESULT_BUCKET: !Ref ResultsBucket
          RESULT_TOPIC_ARN: !Ref ResultsSNSTopic
    DeletionPolicy: Retain

  # Lambda Permissions for S3
  LambdaPermissionS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SentraScannerFunction
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
    DeletionPolicy: Retain

Outputs:
  ResultsBucketName:
    Description: "S3 bucket where results are stored."
    Value: !Ref ResultsBucket

  ResultsSNSTopicARN:
    Description: "SNS Topic ARN for publishing results."
    Value: !Ref ResultsSNSTopic

  LambdaFunctionName:
    Description: "Name of the Lambda function."
    Value: !Ref SentraScannerFunction
